# Generated by Django 4.1 on 2024-02-15 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_post", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                ("cuerpo_post", models.TextField()),
                ("publicado", models.DateTimeField(default=django.utils.timezone.now)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("BR", "Borrador"), ("PB", "Publicado")],
                        default="BR",
                        max_length=2,
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["publicado"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["publicado"], name="blogppal_po_publica_83941f_idx"
            ),
        ),
    ]
